### ISSUE TITLE
Update 903 schema for OC3: Activity

### ISSUE THREAD

**Issue by MichaelHanksSF** [SocialFinanceDigitalLabs/liia-tools#183]
In returns from before the 21-22 FY return, the following codes were acceptable values for the field Activity in the OC3 return: "F3", "P3".

We need to update the schema to allow these as legal values, preferably so that they are acceptable for returns before 2022 and not acceptable for returns from 2022 onwards.

**Comment by StephenCarterLIIA** [comment]
Fixed in issue #187
