### ISSUE TITLE
Quick fixes for CSWW

### ISSUE THREAD

**Issue by patrick-troy** [SocialFinanceDigitalLabs/liia-tools#191]
- [x] Combining/Moving modules
  - [x] Combine FTESum.py and FTESum_2020.py modules together
  - [x] Combine seniority.py, progress.py and seniroty_forecast_5c.py modules together
  - [x] Remove the unnecessary reloading of ‘SeniorityComp.csv’/dfSen dataframe in seniroty_forecast_5c.py
  - [x] Remove the code that produces FTESum_5d.xlsx from seniority_forecast_5c.py as this is repeated in FTESum.py
  - [x] Move the OrgRoleDict and SeniorityCodeDict from seniority_forecast_5c.py to the converter.py module and import them

- [x] Removing clutter
  - [x] Remove unused imported packages
  - [x] Remove unused lines of code that have been commented out e.g. line 24 in progressed.py
  - [x] Remove unused lines of code/repeated code e.g. line 11 in FTESum_2020.py
  - [x] Correct spelling errors e.g. on line 23 of pivotGen.py
  - [x] Avoid unnecessary renaming of dataframes in the seniority_forecast_04.py module
  - [x] Rename columns rather than duplicating and dropping columns in the seniority_forecast_04.py module

- [x] Fixing errors
  - [x] The OrgRoleDict dictionary in the seniorty_forecast_5c.py module assumes that OrgRole is always known, this is not the case and the function will break with unknown OrgRole values (which are valued). Find a way to fix this. 

- [x] Fixing module import paths
  - [x] Update import paths to reflect new folder structure, for example, rather than
  import work_path
  use import liiatools.datasets.social_work_workforce.SWFtools.util.work_path

**Comment by StephenCarterLIIA** [comment]
Pull request #205 submitted
